### ISSUE TITLE
CommandError: You have not set ASGI_APPLICATION, which is needed to run the server.

### ISSUE THREAD

**Issue by darkane188** [django-wiki/django-nyt#94]
![image](https://user-images.githubusercontent.com/10376033/74599661-7eea1880-5053-11ea-9692-b5de07cb0cf7.png)

**Comment by benjaoming** [comment]
Yes, the "test-project" application was written to do local development/demoing back in the Django 1.11 days. Try to downgrade Django and channels.

Why is it that you need the test project? Would you be able to make it work and submit a PR?

**Comment by benjaoming** [comment]
Closing this, but I think we need it to be happening to keep django-nyt alive: https://github.com/django-wiki/django-nyt/issues/130
